[package]
authors = ["David Weis <dweis7@gmail.com>"]
edition = "2021"
name = "mqtt-router"
publish = false
version = "0.2.1"

[dependencies]
async-trait = "0.1"
itertools = "0.12"
thiserror = "1.0"
anyhow = "1.0"

[dev-dependencies]
rumqttc = "0.23.0"
tokio = {version = "1", features = ["full"]}
