[package]
authors = ["David Weis <dweis7@gmail.com>"]
edition = "2021"
name = "mqtt-router"
publish = false
version = "0.1.3"

[dependencies]
async-trait = "0.1"
itertools = "0.10.3"
thiserror = "1.0"

[dev-dependencies]
rumqttc = "0.20.0"
tokio = {version = "1", features = ["full"]}
